mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.routes.polls')),
    path('admin/', admin.site.urls),
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/polls/routes/polls.py
from django.urls import path
from polls import views
from polls.myviews import main

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('main/', main.index, name='main-index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from .models import Question
title = "My Django App"
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list, 'title': title}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk= question_id)
    except Question.DoesNotExist:
        return render(request, 'polls/404.html', {'title': title})
    return render(request, 'polls/details.html', {'question': question, 'title': title})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

mysite/polls/templates/polls/details.html
{% include "./header.html" with title=title %}
            <div class="card" style="width:25rem;">            
                <ul class="list-group">
                    <li class="list-group-item active text-center">{{ question.question_text }}</li>
                    {% for choice in question.choice_set.all %}
                        <li class="list-group-item">{{ choice.choice_text }}</li>
                    {% endfor %}
                </ul>
            </div>        
        </div>
    </body>
</html>

mysite/polls/templates/polls/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Polls App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Image and text -->
    <nav class="navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="http://localhost:8000/polls">
            {{ title }}
        </a>
    </nav>
    <div class="container-fluid pt-4">

mysite/polls/templates/polls/index.html
        {% include "./header.html" with title=title %}
        <div class="card" style="width:25rem;">            
            <ul class="list-group">
                <li class="list-group-item active text-center">Questions</li>
                {% if latest_question_list %}
                    {% for question in latest_question_list %}
                        <li class="list-group-item">
                            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                        </li>
                    {% endfor %}
                {% else %}
                    <li class="list-group-item">No polls are available.</li>
                {% endif %}
            </ul>
        </div>
        
    </div>
    </body>
</html>